name: CI-CD workflow

permissions:
  id-token: write
  contents: read

on:
    push:
        branches:
            - main
            - develop
    pull_request: 
        branches: 
            - main
jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Setup Node.js
              uses: actions/setup-node@v7
              with:
                node-version: latest
            - run: npm ci
            - run: npm run build
            - run: npm test
            - name: Upload build artifact
              uses: actions/upload-artifact@v4
              with:
                name: deployment-artifact
                path: out/
                
    publish:
        needs: build-and-test
        environment: production

        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
            
        steps:
            - name: login to azure
              uses: azure/login@v2
              with:
                client-id: ${{ vars.AZURE_CLIENT_ID }}
                tenant-id: ${{ vars.AZURE_TENANT_ID }}
                subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
                

            - name: Download build artifact
              uses: actions/download-artifact@v4
              with:
                name: deployment-artifact
                path: out/

            - name: deploy to azure web app
              uses: azure/webapps-deploy@v3
              with:
                app-name: next
                package: out/
