name: CI/CD Pipeline
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build-and-test:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'
            - run: npm ci
            - run: npm run build
            - run: npm test

    build-and-push-docker-image:
        permissions:
            id-token: write
            contents: read
        environment: production
        runs-on:
            - ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: azure/login@v2
              with:
                  client-id: ${{ vars.AZURE_CLIENT_ID }}
                  tenant-id: ${{ vars.AZURE_TENANT_ID }}
                  subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
            - name: Login to ACR
              run: az acr login --name acrddi
            - uses: docker/build-push-action@v4
              with:
                    context: .
                    push: true
                    tags: acrddi/fictional-adventure:latest
                  